# Site settings
title: liulunet
name: liulu
email: liulunet#live.com
description: > # this means to ignore newlines until "baseurl:"
  This is a Jekyll blog on Github Pages by liulu.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://liulunet.github.io" # the base hostname & protocol for your site
twitter_username: liulunet
github_username:  liulunet
weibo_username: liulunet

# Build settings
timezone: Asia/Shanghai
markdown: kramdown
